### ISSUE TITLE
Support Multiple `pathTransform` Mappings

### ISSUE THREAD

**Issue by jamiejackson** [softwareCobbler/luceedebug#14]
I think I need multiple `pathTransform`s.

I think (because I'm new to vs code) I want a multi-root workspace as follows:

* my_site_cfml
* mura_cfml

Since I bake the Mura core into my image, it's not available in my_site_cfml. I have Mura checked out separately.

I'd want something like:

```json
"pathTransform": [
  {
    "idePrefix": "${workspaceFolder}/cfml/deployment_root",
    "cfPrefix": "/var/www"
  },
  {
    // not sure the most semantic way to specify this path in vs code, but this would probably work
    "idePrefix": "${workspaceFolder}/../hudx_mura_fork/app/core",
    "cfPrefix": "/var/www/wwwroot/core/"
  },
]
```

I could probably work around it with symlinks or something, but it would be good to have native support.

It might get a little tricky because layering would need to be accommodated. (It would probably make sense to have increasing precedent as you append to the `pathTransform` array.

**Comment by softwareCobbler** [comment]
(huh didn't mean to close)

This is now `pathTransforms` (plural), but the syntax is as you show it - a JSON array literal. It can be of length 0, 1, or many. The first matching prefix wins. If no match is found, no transform takes place.

**Comment by softwareCobbler** [comment]
I don't know how it'll play with a multiroot workspace, I think a debug launch config is per workspace, so `${workspaceRoot}` is always a single value. It would seem natural for it to find files across both workspaces, assuming its being given absolute paths.

**Comment by jamiejackson** [comment]
Thanks! I'll try it out in the next few days.

**Comment by jamiejackson** [comment]
I haven't tried it with multiple mappings yet but I have verified that a single mapping does work inside of the new array structure. PR to fix up the docs and references: #15

I'll report back when I've verified the behavior of multiple mappings.

**Comment by jamiejackson** [comment]
@softwareCobbler , could you describe how precedence works when multiple (potentially "nested") mappings are specified? I looked at the new munging code but it wasn't obvious how it worked, from a quick read-through.

**Comment by jamiejackson** [comment]
Never mind, I just reread your comments:

> The first matching prefix wins.

That's what we've got already, so I'll send a documentation PR.

**Comment by jamiejackson** [comment]
Added documentation to #15.

**Comment by jamiejackson** [comment]
> I don't know how it'll play with a multiroot workspace, I think a debug launch config is per workspace, so ${workspaceRoot} is always a single value. It would seem natural for it to find files across both workspaces, assuming it's being given absolute paths.

I found the `${workspaceFolder:my_folder_name}` syntax in the VS code docs. It's working well, so far. I like that it (along with the `hudx.code-workspace` workspace definition) is portable, so my team can use it from SCM without needing personal versions.

```json
"configurations": [
    {
        "type": "cfml",
        "request": "attach",
        "name": "Debug HUDX Lucee",
        "hostName": "local.hudx.net",
        "port": 10000,
        "pathTransforms": [
            {
                "idePrefix": "${workspaceFolder:mura}/app/core",
                "cfPrefix": "/var/www/wwwroot/core"
            },
            {
                "idePrefix": "${workspaceFolder:hudx}/cfml/deployment_root",
                "cfPrefix": "/var/www"
            },
        ]
    }
]
```

I may end up documenting this, too.
