### ISSUE TITLE
Performance Overhead

### ISSUE THREAD

**Issue by chapmandu** [softwareCobbler/luceedebug#35]
It appears that having the luceedebug.jar installed has a significant performance overhead.

The results below is a snippet of some integration test output, with and without the luceedebug.jar loaded via java args.

Note that I don't have the step debugger running in vscode, it's simply installed, and running my test suite.

I'm happy to live with a bit of overhead, but my test suite's execution time goes from 6 mins to 28 mins.

I concede that the "listings" controller does a fair bit of work, but the "mfadevices" controller really does not. Interestingly, the memory and CPU don't really run as high as I would have expected in relation to the response time.

**Without luceedebug.jar loaded**
```
listings.converttolisting 1693ms
listings.create 2706ms
listings.details 3116ms
listings.documents 1105ms
listings.edit 3300ms
listings.index 820ms
listings.listingfields.create 334ms
listings.listingfields.update 214ms
listings.modalform 618ms
listings.new 2732ms
listings.update 2210ms
listings.updatesettle 1686ms
mfadevices.create 128ms
mfadevices.delete 117ms
mfadevices.edit 171ms
mfadevices.new 62ms
mfadevices.show 217ms
```

**With luceedebug.jar loaded**
```
listings.converttolisting 7559ms
listings.create 16588ms
listings.details 16522ms
listings.documents 5013ms
listings.edit 28354ms
listings.index 4004ms
listings.listingfields.create 1328ms
listings.listingfields.update 824ms
listings.modalform 2508ms
listings.new 29730ms
listings.update 16355ms
listings.updatesettle 7555ms
mfadevices.create 613ms
mfadevices.delete 798ms
mfadevices.edit 1316ms
mfadevices.new 357ms
mfadevices.show 1688ms
```

![image](https://user-images.githubusercontent.com/1092563/227063512-f4ad8b8a-7f7f-4158-9a7a-18976fd4d202.png)

I'm happy to help wherever I can.

**Comment by softwareCobbler** [comment]
Yeah, there's a perf overhead; but I don't see 400+% percent, I run like 20% which isn't great but enough to not really be noticeable for my dev work. 

I have a test suite putting out numbers over 4 runs like
```
plain             with debugger running (vscode not attached)
270,128ms         333,610ms
286,091ms         324,133ms
276,942ms         322,505ms
275,889ms         327,482ms
------            -------
avg 277262.5ms    326932.5ms   overhead 18%

```

I wonder what the difference in our setups is. My test suite is slow all on its own because it's entirely single threaded -- maybe you are highly concurrent and so are experiencing heavy contention on some ConcurrentMaps that doesn't happen over here.

**Comment by chapmandu** [comment]
Our test suite is also concurrent, but makes (synchronous) requests to an endpoint for each test package. So lots of small requests rather than one long one.

**Comment by Symbianx** [comment]
I've been trying this out as well and was am super excited but noticed a big performance degradation.
A request that would take 4 seconds i now taking 30 seconds in a 4 core VM.

Is there anything I can provide to help with debugging this issue?

**Comment by softwareCobbler** [comment]
@Symbianx can you take a perf trace via JMC or a similar tool? I am curious where it's spending its time. What platform are you on -- you guys both on Windows?

**Comment by chapmandu** [comment]
Hey guys, I haven't managed to do any performance analysis yet, but FYI I'm on Ubuntu based Linux.

**Comment by chapmandu** [comment]
I really should have given these details in my initial post:

Ubuntu Linux
Lucee 5.3.10.97
Commandbox Docker Container

**Comment by softwareCobbler** [comment]
Neat, that's almost my setup, too. That rules out the "it's some weird Windows phenomenon" theory.

You might find something interesting with [JMC](https://www.oracle.com/java/technologies/javase/products-jmc8-downloads.html)

I get a good connection to it spawning Java with 
```
-Dcom.sun.management.jmxremote.port=<some-port>
-Dcom.sun.management.jmxremote.authenticate=false
-Dcom.sun.management.jmxremote.ssl=false
```

I don't have any good theories on a particular culprit at the moment. Do the workloads involve spawning thousands of threads which are all expected to complete very quickly?

**Comment by chapmandu** [comment]
It will probably be a few days before I get to tinker with it again, but my application doesn't use any cfthread or async functions. FWIW I use the cfwheels framework. I'd be interested to hear what setup @Symbianx uses, perhaps there is a common factor?

**Comment by Symbianx** [comment]
In our case, we're using the [commandbox docker image](https://hub.docker.com/r/ortussolutions/commandbox) based on alpine. This runs together with coldbox as the framework.

**Comment by Symbianx** [comment]
Alright, I bring some more info!
I ran JMC and one of the things it mentions is that 812000 exceptions were thrown in a 1 min period, during the execution of the 30s requests.

Looks like the majority of the exceptions were started by `DebugFrame luceedebug.coreinject.DebugManager.pushCfFrame_worker(PageContext, String, int)`. Please see the attached screenshot.

Due to the nature of the software, I prefer to not share the full JMC recording file but let me know if there's more info you would like me to share.

![image](https://user-images.githubusercontent.com/4512703/234268980-9723f117-04ba-48fc-9179-36c55cd16cd9.png)

**Comment by Symbianx** [comment]
Indeed, you are correct about the `session scope is not enabled` one, was able to track it down to https://github.com/softwareCobbler/luceedebug/blob/master/luceedebug/src/main/java/luceedebug/coreinject/DebugFrame.java#L97

Was trying to do the same backtrack to the `null` one but it also points towards the same line in `DebugFrame.java`. This is my first time using JMC though, I could be doing something wrong.

![image](https://user-images.githubusercontent.com/4512703/234275598-c591702b-1e58-49fa-a263-112a1c5b008c.png)

**Comment by softwareCobbler** [comment]
Strong candidates are `tryGetFrameName` and all the other invocations of `getScopeOrNull`. I don't think too much else can throw (so frequently) from this area.

**Comment by Symbianx** [comment]
Alright, changing [this line](https://github.com/softwareCobbler/luceedebug/blob/master/luceedebug/src/main/java/luceedebug/coreinject/DebugFrame.java#L97) to `null` as you mentioned fixed the slow performance and the debugger still works.

Should I make a PR to set it to null or will this cause issues with something else?

**Comment by Symbianx** [comment]
I found a method to determine wether session management is enabled or not. (Check #39)
However I'm not able to test it since we have it disabled.

**Comment by softwareCobbler** [comment]
@Symbianx I ran it over here, and continue to have session scope in debug output, so it seems like it does what it says. I wonder if your PR solves @chapmandu's slowness, too?

**Comment by chapmandu** [comment]
I'll try to reinstall and test today.. interestingly I also have sessions disabled. Good work!

**Comment by adamzenu** [comment]
I've run our test suite with the new jar & without the jar installed. There is now about a 5% overhead which I am very happy to live with.. Well done!!
