### ISSUE TITLE
Extension Installation Questions & Target CFML

### ISSUE THREAD

**Issue by jamiejackson** [softwareCobbler/luceedebug#8]
These might be very basic questions but I'm new to VS Code, much less VS Code non-marketplace extensions and VS Code debuggers. (I come from Eclipse => IntelliJ.)

I'm not sure how the luceedebug extension gets installed into VS Code. (Or how to uninstall it once it's installed.)

On a possibly related note, I'm not sure what the recommended way is to incorporate this into one's own CFML project. I can `cd vscode-client && code .`, then open my CFML project source root folder, but that's clunky to do each time and for each project.

Note that I don't really know about VS Code workspaces yet, so please be explicit about if/how to use them for setup of one's project.

Could you explain those, please?

**Comment by jamiejackson** [comment]
I installed via the Marketplace, which worked, I think. (I'm getting errors from the Adobe ColdFusion Builder extension, which are probably unrelated and possibly _not_ an impediment to debugging). I still haven't gotten the connection working but I opened another ticket for that (#10).

Thanks for the Marketplace push, which answers my "installation" question from the perspective of an end-user.

However, regarding the perspective of an _extension_ developer: If I wanted to hack at the extension while also using my own CFML application's source, how would I set up VS Code and/or structure the workspace?

(I want to document this stuff so that others can learn from my snags.)

**Comment by softwareCobbler** [comment]
From a developer perspective, after making any desired code changes, the project needs to get rebuilt (`npm run build-dev-{windows,linux}`), and then run via the `extension` debug launch config (see attached image). This spawns an "extension development host", which is an instance of vscode with the extension loaded for development purposes, with a debugger wired up so you can set breakpoints in the extension itself.

![image](https://user-images.githubusercontent.com/18746216/206921036-14aa322f-a035-4a8b-b9f7-d756033231c4.png)
